/* TABLE 생성 */
create table ORDERS(
OS_STCODE   NCHAR(10),
OS_SECODE    NCHAR(3),
OS_DATE   DATE,
OS_GCCODE   NCHAR(16),
OS_GCSGCODE NCHAR(8),
OS_TACODE   NUMBER(3)
)tablespace users;

create public synonym OS for POSDBA2.ORDERS;

create table ORDERSDETAILS(
OD_OSSTCODE   NCHAR(10),
OD_OSSECODE    NCHAR(3),
OD_OSDATE   DATE,
OD_OSGCCODE   NCHAR(16),
OD_GCSGCODE NCHAR(8),
OD_OSTACODE   NUMBER(3),
OD_SMCODE   NCHAR(10),
OD_DATE DATE,
OD_QUANTITY NVARCHAR2(2)
)tablespace users;

create public synonym OD for POSDBA2.ORDERSDETAILS;

create table SALESDETAILS(
SD_OSSTCODE   NCHAR(10),
SD_OSSECODE    NCHAR(3),
SD_OSDATE   DATE,
SD_OSGCCODE   NCHAR(16),
SD_GCSGCODE NCHAR(8),
SD_OSTACODE   NUMBER(3),
SD_DATE   NCHAR(10),
SD_APPROVALNUM NCHAR(9),
SD_PRICE NVARCHAR2(10),
SD_INSTALLMENT  NVARCHAR2(2),
SD_CHARDNUM NVARCHAR2(16)
)tablespace users;

create public synonym SD for POSDBA2.SALESDETAILS;

/*PK*/

/*FK*/
alter table storetables
drop constraint TA_STCODE_FK;

ALTER TABLE STORETABLES
ADD CONSTRAINT TA_STCODE_FK foreign KEY(TA_STCODE) references STORES(ST_CODE);

/* CONSTRAINT */
alter table STOREGROUP
modify SG_NAME not null
modify SG_CEO not null;

alter table STORECATEGORIES
modify SC_NAME not null;

alter table STORES
modify ST_NAME not null
modify ST_ZIPCODE not null
modify ST_ADDR not null
modify ST_ADDRDETAIL not null
modify ST_PHONE not null;

alter table STORES
modify ST_SICODE default 'ST+000+(S:N:B)';

alter table STOREIMAGES
modify SI_NAME not null
modify SI_LOC not null;

alter table STOREEMPLOYEES
modify SE_NAME not null;

alter table STOREEMPLOYEES
modify SE_PIN default '123456';

alter table STOREMENUES
modify SM_NAME not null;

alter table STORETABLES
modify TA_SEAT default 4
modify TA_TOP default '10px'
modify TA_LEFT default '10px'
modify TA_WIDTH default '15%'
modify TA_HEIGHT default '20%';

alter table ACCESSLOG
modify AC_DATE default sysdate
modify AC_IP not null
modify AC_TYPE not null;

alter table COSTPRICEMGR
modify CP_COST not null
modify CP_PRICE not null;

alter table GROUPCUSTOMERS
add constraint GC_ID_CHECK_UK UNIQUE (GC_ID, GC_CHECK)
modify GC_NAME not null;

alter table ORDERS
ADD constraint OS_ST_SE_DATE_GC_SG_TA_PK primary key(OS_STCODE, OS_SECODE, OS_DATE, OS_GCCODE, OS_GCSGCODE, OS_TACODE);

alter table ORDERS
add constraint OS_STCODE_SECODE_FK foreign KEY(OS_STCODE, OS_SECODE) references STOREEMPLOYEES(SE_STCODE, SE_CODE)
add constraint OS_GCCODE_GCSGCODE_FK foreign KEY(OS_GCCODE, OS_GCSGCODE) references GROUPCUSTOMERS(GC_CODE, GC_SGCODE);

alter table ORDERSDETAILS
add constraint OS_OD_FK foreign KEY(OD_OSSTCODE, OD_OSSECODE, OD_OSDATE, OD_OSGCCODE, OD_GCSGCODE, OD_OSTACODE) references ORDERS(OS_STCODE, OS_SECODE, OS_DATE, OS_GCCODE, OS_GCSGCODE, OS_TACODE);

alter table ORDERSDETAILS
add constraint OS_SMCODE_FK foreign KEY(OD_OSSTCODE, OD_SMCODE) references STOREMENUES(SM_STCODE, SM_CODE);



alter table SALESDETAILS
add constraint SD_OD_FK foreign KEY(SD_OSSTCODE, SD_OSSECODE, SD_OSDATE, SD_OSGCCODE, SD_GCSGCODE, SD_OSTACODE) references ORDERS(OS_STCODE, OS_SECODE, OS_DATE, OS_GCCODE, OS_GCSGCODE, OS_TACODE);

alter table SALESDETAILS
add constraint SD_PK primary key(SD_OSSTCODE, SD_OSSECODE, SD_OSDATE, SD_OSGCCODE, SD_GCSGCODE, SD_OSTACODE, SD_DATE);

/* DEV 계정생성 */
create user keonho
IDENTIFIED BY "1234"
default tablespace users
quota 20M on users;

create user jyj
IDENTIFIED BY "1234"
default tablespace users
quota 20M on users;

create user jhw
IDENTIFIED BY "1234"
default tablespace users
quota 20M on users;

create user changyong
IDENTIFIED BY "1234"
default tablespace users
quota 20M on users;

/* 권한 부여 */
GRANT CREATE SESSION, resource TO keonho;
GRANT CREATE SESSION, resource TO jyj;
GRANT CREATE SESSION, resource TO jhw;
GRANT CREATE SESSION, resource TO changyong;

grant alter any table to DBA2;
grant alter any table to keonho;
grant alter any table to jyj;
grant alter any table to jhw;
grant alter any table to changyong;

grant select, insert, update on STORES to keonho;
grant select, insert, update on STORES to jyj;
grant select, insert, update on STORES to jhw;
grant select, insert, update on STORES to changyong;

grant select, insert, update on STOREIMAGES to keonho;
grant select, insert, update on STOREIMAGES to jyj;
grant select, insert, update on STOREIMAGES to jhw;
grant select, insert, update on STOREIMAGES to changyong;

grant select, insert, update on STOREGROUP to keonho;
grant select, insert, update on STOREGROUP to jyj;
grant select, insert, update on STOREGROUP to jhw;
grant select, insert, update on STOREGROUP to changyong;

grant select, insert, update on STOREEMPLOYEES to keonho;
grant select, insert, update on STOREEMPLOYEES to jyj;
grant select, insert, update on STOREEMPLOYEES to jhw;
grant select, insert, update on STOREEMPLOYEES to changyong;

grant select, insert, update on STORECATEGORIES to keonho;
grant select, insert, update on STORECATEGORIES to jyj;
grant select, insert, update on STORECATEGORIES to jhw;
grant select, insert, update on STORECATEGORIES to changyong;

grant select, insert, update on STORECATEGORIES to keonho;
grant select, insert, update on STORECATEGORIES to jyj;
grant select, insert, update on STORECATEGORIES to jhw;
grant select, insert, update on STORECATEGORIES to changyong;

grant select, insert, update on STOREMENUES to keonho;
grant select, insert, update on STOREMENUES to jyj;
grant select, insert, update on STOREMENUES to jhw;
grant select, insert, update on STOREMENUES to changyong;

grant select, insert, update on STORETABLES to keonho;
grant select, insert, update on STORETABLES to jyj;
grant select, insert, update on STORETABLES to jhw;
grant select, insert, update on STORETABLES to changyong;

grant select, insert, update on ACCESSLOG to keonho;
grant select, insert, update on ACCESSLOG to jyj;
grant select, insert, update on ACCESSLOG to jhw;
grant select, insert, update on ACCESSLOG to changyong;

grant select, insert, update on COSTPRICEMGR to keonho;
grant select, insert, update on COSTPRICEMGR to jyj;
grant select, insert, update on COSTPRICEMGR to jhw;
grant select, insert, update on COSTPRICEMGR to changyong;

grant select, insert, update on GROUPCUSTOMERS to keonho;
grant select, insert, update on GROUPCUSTOMERS to jyj;
grant select, insert, update on GROUPCUSTOMERS to jhw;
grant select, insert, update on GROUPCUSTOMERS to changyong;

/* 그룹코드 시퀀스 생성 */
CREATE SEQUENCE SG_CODE_SEQUENCE
       INCREMENT BY 1
       START WITH 0000001
       MINVALUE 0000001
       MAXVALUE 9999999
       NOCYCLE
       NOCACHE
       NOORDER;
       
/* 제약 조건 */
add constraint PK_CP_SMSTCODE_SMCODE_DATE primary key(CP_SMSTCODE, CP_SMCODE, CP_DATE);
Add constraint COSTPRICEMGR foreign key () references ();

CONSTRAINT pk_id PRIMARY KEY

alter table changyong.ACCESSHISTORY
modify AH_DATE DEFAULT sysdate
modify AH_STATE not null;

alter table changyong.TODO
modify TD_FEEDBACK DEFAULT 'NONE'
modify TD_STATE DEFAULT 'B'
modify TD_ACTIVATION DEFAULT 'A';
commit;

select *
from SG;

delete
from storegroup;

DROP SEQUENCE SG_CODE_SEQUENCE;
commit;

CREATE SEQUENCE SG_CODE_SEQUENCE
    START WITH 1000000
    INCREMENT BY 1
    MAXVALUE 9999999
    MINVALUE 1000000;
    
    
SELECT SG_NAME AS GROUPNAME FROM SG WHERE SG_NAME = '씨유';

/* 중복검사를 위한 임시 저장 테이블 */
CREATE TABLE TEMP(
  TEMP_GROUPNAME    NVARCHAR2(20)   NOT NULL
)TABLESPACE USERS;

-- GRANT
GRANT SELECT, INSERT, DELETE ON POSDBA2.TEMP TO changyong;
GRANT SELECT, INSERT, DELETE ON POSDBA2.TEMP TO keonho;
GRANT SELECT, INSERT, DELETE ON POSDBA2.TEMP TO jyj;
GRANT SELECT, INSERT, DELETE ON POSDBA2.TEMP TO jhw;

select * from DUPGROUPNAME;

-- 중복체크 VIEW
CREATE OR REPLACE VIEW DUPGROUPNAME
AS
SELECT SG_NAME AS GROUPNAME FROM POSDBA2.SG
UNION 
SELECT TEMP_GROUPNAME AS GROUPNAME FROM POSDBA2.TEMP;
  -- GRANT
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO changyong;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO keonho;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO jyj;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO jhw;

SELECT * FROM POSDBA2.DUPGROUPNAME WHERE GROUPNAME = 'Hoon';

-- 중복이 안된 경우 TEMP테이블 INSERT
INSERT INTO POSDBA2.TEMP(TEMP_GROUPNAME) VALUES('changyong');
COMMIT;

SELECT * FROM POSDBA2.TEMP;
select * from sg;

delete
from TEMP;

delete
from sg;

delete
from st;

commit;

INSERT INTO ST(ST_CODE, ST_NAME, ST_ZIPCODE, ST_ADDR, ST_ADDRDETAIL, ST_PHONE, ST_SGCODE)
VALUES('1111111111', '씨유점', '12345', '주소입력중', '세부주소입력중', '01049153515', '');

SELECT * FROM POSDBA2.TEMP WHERE TEMP_GROUPNAME = 'changyong';

-- 취소시
DELETE FROM POSDBA2.TEMP WHERE TEMP_GROUPNAME = 'Hoon';
COMMIT;

-- 최종 확정 시
INSERT INTO POSDBA2.SG(SG_CODE, SG_NAME, SG_CEO, SG_PIN) VALUES();
DELETE FROM POSDBA2.TEMP WHERE TEMP_GROUPNAME = 'Hoon';
COMMIT;

select * from st;
select * from sc;
select * from sg;
select * from SE;

INSERT INTO SE(SE_STCODE, SE_CODE, SE_SCL, SE_NAME, SE_PIN, SE_SICODE)
VALUES('1234567890', '000', 'L3', '임창용', '123456', '1234567890000S');
INSERT INTO SE(SE_STCODE, SE_CODE, SE_SCL, SE_NAME, SE_PIN, SE_SICODE)
VALUES('1234567890', '001', 'L3', '정현우', '123456', '1234567890001S');
INSERT INTO SE(SE_STCODE, SE_CODE, SE_SCL, SE_NAME, SE_PIN, SE_SICODE)
VALUES('1234567890', '002', 'L3', '박건호', '123456', '1234567890002S');
INSERT INTO SE(SE_STCODE, SE_CODE, SE_SCL, SE_NAME, SE_PIN, SE_SICODE)
VALUES('1234567890', '003', 'L3', '정영준', '123456', '1234567890003S');

DELETE from StoreGroup;
DELETE from st;
DELETE from Temp;
DELETE from sc;
commit;


ALTER TABLE STORECATEGORIES
RENAME Column SC_SGCODE to SC_STCODE;

ALTER TABLE STORECATEGORIES
drop CONSTRAINT SC_SGCODE_FK;

ALTER TABLE STORECATEGORIES
ADD CONSTRAINT SC_STCODE_FK foreign KEY(SC_STCODE) references STORES(ST_CODE);
ADD CONSTRAINT SC_STCODE_PK primary KEY(SC_STCODE);

/* CREATE EMPINFO VIEW  */
CREATE OR REPLACE VIEW EMPINFO
AS
SELECT ST_SGCODE AS GROUPCODE, ST_CODE AS STORECODE, ST_NAME AS STORENAME,SE_CODE AS EMPCODE, SE_SCL AS EMPLEV, SE_NAME AS EMPNAME, SE_PIN AS EMPPIN, SE_SICODE AS EMPIMGCODE FROM ST
INNER JOIN SE ON ST.ST_CODE = SE.SE_STCODE;

SELECT * FROM ST
INNER JOIN SE ON ST.ST_CODE = SE.SE_STCODE;

select *
from Accesslog;

select *
from st;

update st
set st_name = 'ICIA 학원', st_addr = '인천', st_addrdetail='학익동', st_phone = '01012345678';
commit;

  -- GRANT
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO changyong;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO keonho;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO jyj;
GRANT SELECT ON POSDBA2.DUPGROUPNAME TO jhw;


/***************************************************************************                           
                            Dynamic Web POS   
 
 2022.11.29 ~ 2022.12.26
 Test : 2022. 12. 27 ~ 2022. 12. 31
****************************************************************************/
/* USER CREATION 
   DBA : WEBDBA / 8520
   DEV : WEBDEV / 8520
*/
  -- SYS
  CREATE USER WEBDBA 
  IDENTIFIED BY 8520 
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;
    -- GRANT
    GRANT DBA TO WEBDBA;
  -- SYS
  CREATE USER WEBDEV
  IDENTIFIED BY "8520"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;
    -- GRANT
    GRANT CONNECT, RESOURCE TO WEBDEV;

/* WEBDBA : 1. REF:SG STOREGROUP */
CREATE TABLE STOREGROUP(
  SG_CODE   NCHAR(8),
  SG_NAME   NVARCHAR2(20)   NOT NULL,
  SG_CEO    NVARCHAR2(5)    NOT NULL,   
  SG_PIN    NCHAR(6)        NOT NULL
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STOREGROUP
  ADD CONSTRAINT SG_CODE_PK PRIMARY KEY(SG_CODE);
  -- SYNONYM
  CREATE SYNONYM SG FOR WEBDBA.STOREGROUP;
  -- GRANT 
  GRANT SELECT ON WEBDBA.SG TO WEBDEV;
  GRANT SELECT, UPDATE, INSERT ON WEBDBA.STOREGROUP TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.SG;
  
/* WEBDBA : 2. MAIN:GC GROUPCUSTOMERS */
CREATE TABLE GROUPCUSTOMERS(
  GC_SGCODE NCHAR(8),
  GC_CODE   NCHAR(16)       NOT NULL,
  GC_ID   NVARCHAR2(10)    NOT NULL,   
  GC_NAME   NCHAR(5)        NOT NULL,
  GC_CHECK  NCHAR(8)
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE GROUPCUSTOMERS
  ADD CONSTRAINT GC_SGCODE_CODE_PK      PRIMARY KEY(GC_SGCODE, GC_CODE)
  ADD CONSTRAINT GC_SGCODE_FK           FOREIGN KEY(GC_SGCODE) 
                                        REFERENCES STOREGROUP(SG_CODE)
  ADD CONSTRAINT GC_ID_UK               UNIQUE(GC_ID)
  ADD CONSTRAINT GC_CHECK_UK            UNIQUE(GC_CHECK);
  -- SYNONYM
  CREATE SYNONYM GC FOR WEBDBA.GROUPCUSTOMERS;
  -- GRANT 
  GRANT SELECT ON WEBDBA.GC TO WEBDEV;
  GRANT SELECT, UPDATE, INSERT ON WEBDBA.GROUPCUSTOMERS TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.GC;
  
/* WEBDBA : 3. KEY:ST STORES */
CREATE TABLE STORES(
  ST_CODE           NCHAR(10),
  ST_NAME           NVARCHAR2(50)   NOT NULL,      
  ST_ZIPCODE        NCHAR(5)        NOT NULL,  
  ST_ADDR           NVARCHAR2(100)  NOT NULL,
  ST_ADDRDETAIL     NVARCHAR2(100)  NOT NULL,
  ST_PHONE          NVARCHAR2(11)   NOT NULL,
  ST_SICODE         NCHAR(14),
  ST_SGCODE         NCHAR(8)        NOT NULL
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STORES
  ADD CONSTRAINT ST_CODE_PK         PRIMARY KEY(ST_CODE)
  ADD CONSTRAINT ST_SGCODE_FK       FOREIGN KEY(ST_SGCODE) 
                                    REFERENCES STOREGROUP(SG_CODE);
  -- SYNONYM
  CREATE SYNONYM ST FOR WEBDBA.STORES;
  -- GRANT 
  GRANT SELECT ON WEBDBA.ST TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STORES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.ST;
  
/* WEBDBA : 4. REF:SI STOREIMAGES */
CREATE TABLE STOREIMAGES(
  SI_CODE   NCHAR(14),
  SI_NAME   NVARCHAR2(20)   NOT NULL,
  SI_LOC    NCHAR(29)       NOT NULL 
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STOREIMAGES
  ADD CONSTRAINT SI_CODE_PK         PRIMARY KEY(SI_CODE);
  -- SYNONYM
  CREATE SYNONYM SI FOR WEBDBA.STOREIMAGES;
  -- GRANT 
  GRANT SELECT ON WEBDBA.SI TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STOREIMAGES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.SI;
  
/* WEBDBA : 5. MAIN:SC STORECATEGORIES */
CREATE TABLE STORECATEGORIES(
  SC_STCODE     NCHAR(10),
  SC_CODE       NCHAR(2)        NOT NULL,
    -- C:상품분류 S:상품상태 L:직원등급 P:가격분류 Z:테이블 구역 O:주문상태 M:결제상태
  SC_NAME       NVARCHAR2(20)   NOT NULL
)TABLESPACE USERS;
  -- CONSTRINTS
  ALTER TABLE STORECATEGORIES
  ADD CONSTRAINT SC_STCODE_CODE_PK      PRIMARY KEY(SC_STCODE, SC_CODE)
  ADD CONSTRAINT SC_STCODE_FK           FOREIGN KEY(SC_STCODE) 
                                        REFERENCES STORES(ST_CODE);
  -- SYNONYM
  CREATE SYNONYM SC FOR WEBDBA.STORECATEGORIES;
  -- GRANT 
  GRANT SELECT ON WEBDBA.SC TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STORECATEGORIES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.SC;
  
/* WEBDBA : 6. MAIN:SE STOREEMPLOYEES */
CREATE TABLE STOREEMPLOYEES(
  SE_STCODE     NCHAR(10), 
  SE_CODE       NCHAR(3),
  SE_SCLEV      NCHAR(2)        DEFAULT 'L3'    NOT NULL,
  SE_NAME       NVARCHAR2(5)    NOT NULL,
  SE_PIN        NCHAR(6)        DEFAULT '123456' NOT NULL,
  SE_SICODE     NCHAR(14)       
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STOREEMPLOYEES
  ADD CONSTRAINT SE_STCODE_CODE_PK      PRIMARY KEY(SE_STCODE, SE_CODE) 
  ADD CONSTRAINT SE_STCODE_FK           FOREIGN KEY(SE_STCODE) 
                                        REFERENCES STORES(ST_CODE)
  ADD CONSTRAINT SE_STCODE_SCL_FK       FOREIGN KEY(SE_STCODE, SE_SCLEV) 
                                        REFERENCES STORECATEGORIES(SC_STCODE, SC_CODE);
  -- SYNONYM
  CREATE SYNONYM SE FOR WEBDBA.STOREEMPLOYEES;
  -- GRANT
  GRANT SELECT ON WEBDBA.SE TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STOREEMPLOYEES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.SE;

/* WEBDBA : 7. ACTION:AL ACCESSLOG */
CREATE TABLE ACCESSLOG(
  AL_SESTCODE   NCHAR(10),
  AL_SECODE     NCHAR(3),
  AL_DATE       DATE    DEFAULT SYSDATE,
  AL_IP         NVARCHAR2(15)   NOT NULL,
  AL_TYPE       NCHAR(1)
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE ACCESSLOG
  ADD CONSTRAINT AL_SESTCODE_SECODE_DATE_PK PRIMARY KEY(AL_SESTCODE, AL_SECODE, AL_DATE)
  ADD CONSTRAINT AL_SESTCODE_SECODE_FK      FOREIGN KEY(AL_SESTCODE, AL_SECODE) 
                                            REFERENCES STOREEMPLOYEES(SE_STCODE, SE_CODE);
 -- SYNONYM
 CREATE SYNONYM AL FOR WEBDBA.ACCESSLOG;
 -- GRANT 
 GRANT SELECT  ON WEBDBA.AL TO WEBDEV;
 GRANT SELECT, INSERT, UPDATE ON WEBDBA.ACCESSLOG TO WEBDEV;
 -- CHECK : WEBDEV
 SELECT * FROM WEBDBA.AL;
 
/* WEBDBA : 8. MAIN:SM STOREMENUES */
CREATE TABLE STOREMENUES(
  SM_STCODE     NCHAR(10), 
  SM_CODE       NCHAR(3),
  SM_SCCAT      NCHAR(2)        NOT NULL,
  SM_NAME       NVARCHAR2(20)   NOT NULL, 
  SM_SCSTATE    NCHAR(2)        DEFAULT 'S1'        NOT NULL,
  SM_COLOR      NCHAR(6)        DEFAULT 'FFFFFF'    NOT NULL,
  SM_SICODE     NCHAR(14)
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STOREMENUES
  ADD CONSTRAINT SM_STCODE_CODE_PK  PRIMARY KEY(SM_STCODE, SM_CODE) 
  ADD CONSTRAINT SM_STCODE_FK       FOREIGN KEY(SM_STCODE) 
                                    REFERENCES STORES(ST_CODE)
  ADD CONSTRAINT SM_STCODE_SCCAT_FK FOREIGN KEY(SM_STCODE, SM_SCCAT) 
                                    REFERENCES STORECATEGORIES(SC_STCODE, SC_CODE)
  ADD CONSTRAINT SM_STCODE_SCSTATE_FK FOREIGN KEY(SM_STCODE, SM_SCSTATE) 
                                    REFERENCES STORECATEGORIES(SC_STCODE, SC_CODE);
  -- SYNONYM
  CREATE SYNONYM SM FOR WEBDBA.STOREMENUES;
  -- GRANT 
  GRANT SELECT ON WEBDBA.SM TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STOREMENUES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.SM;
  
/* WEBDBA : 9. MAIN:CP COSTPRICEMGR */
CREATE TABLE COSTPRICEMGR(
  CP_SMSTCODE   NCHAR(10),
  CP_SMCODE     NCHAR(3),
  CP_DATE       DATE,
  CP_COST       NUMBER(6)       NOT NULL,
  CP_PRICE      NUMBER(6)       NOT NULL,
  CP_SCDIS      NCHAR(2)        NOT NULL,
  CP_COMMENT    NVARCHAR2(50)
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE COSTPRICEMGR
  ADD CONSTRAINT CP_SMSTCODE_SMCODE_DATE_PK    PRIMARY KEY(CP_SMSTCODE, CP_SMCODE, CP_DATE)
  ADD CONSTRAINT CP_SMSTCODE_SMCODE_FK         FOREIGN KEY(CP_SMSTCODE, CP_SMCODE) 
                                               REFERENCES STOREMENUES(SM_STCODE, SM_CODE)
  ADD CONSTRAINT CP_SMSTCODE_SCDIS_FK          FOREIGN KEY(CP_SMSTCODE, CP_SCDIS) 
                                               REFERENCES STORECATEGORIES(SC_STCODE, SC_CODE);
  -- SYNONYM
  CREATE SYNONYM CP FOR WEBDBA.COSTPRICEMGR;
  -- GRANT
  GRANT SELECT ON WEBDBA.CP TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.COSTPRICEMGR TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.CP;
  
/* WEBDBA : 10. MAIN:TA STORETABLES */
CREATE TABLE STORETABLES(
  TA_STCODE     NCHAR(10),
  TA_CODE       NCHAR(3),
  TA_NAME       NVARCHAR2(20),
  TA_SEAT       NUMBER(2)       DEFAULT 4   NOT NULL,
  TA_SCZONE     NCHAR(2)        NOT NULL,
  TA_TOP        NVARCHAR2(4)    DEFAULT '10px'  NOT NULL,
  TA_LEFT       NVARCHAR2(4)    DEFAULT '10px'  NOT NULL,
  TA_WIDTH      NVARCHAR2(4)    DEFAULT '15%'  NOT NULL,
  TA_HEIGHT     NVARCHAR2(4)    DEFAULT '20%'  NOT NULL
)TABLESPACE USERS;
  -- CONSTRAINTS
  ALTER TABLE STORETABLES
  ADD CONSTRAINT TA_STCODE_CODE_PK  PRIMARY KEY(TA_STCODE, TA_CODE)
  ADD CONSTRAINT TA_STCODE_FK           FOREIGN KEY(TA_STCODE)
                                        REFERENCES STORES(ST_CODE)
  ADD CONSTRAINT TA_STCODE_SCZONE_FK    FOREIGN KEY(TA_STCODE, TA_SCZONE)
                                        REFERENCES STORECATEGORIES(SC_STCODE, SC_CODE);
  -- SYNONYM
  CREATE SYNONYM TA FOR WEBDBA.STORETABLES;
  -- GRANT 
  GRANT SELECT ON WEBDBA.TA TO WEBDEV;
  GRANT SELECT, INSERT, UPDATE ON WEBDBA.STORETABLES TO WEBDEV;
  -- CHECK : WEBDEV
  SELECT * FROM WEBDBA.TA;
  
/* SG_CODE >> SEQUENCE */
CREATE SEQUENCE GROUPCODE
  INCREMENT BY  1
  START WITH    1000001
  MAXVALUE      9999999
  MINVALUE      1000001
  NOCYCLE NOCACHE;
  -- GRANT
  GRANT SELECT ON WEBDBA.GROUPCODE TO WEBDEV;
  
  SELECT WEBDBA.GROUPCODE.NEXTVAL FROM DUAL;
  INSERT INTO WEBDBA.SG(SG_CODE, SG_NAME, SG_CEO, SG_PIN) 
          VALUES('S'||WEBDBA.GROUPCODE.NEXTVAL, 'HoonZzang', '후니', '123456');
  
  
  /* JOB : MEMBER JOIN
  TRANSACTION START
  F1. STEP1.HTML  :: 대표등록
     STOREGROUP 
        GROUPNAME GROUPCEO GROUPPIN 
        B1. [INS:SG] SG_CODE + SG_NAME, SG_CEO, SG_PIN 
        >>  [SEL:SG] SG_CODE
*/
  ALTER TABLE STOREGROUP
  ADD CONSTRAINT SG_NAME_UK UNIQUE(SG_NAME);
  -- groupCode
  SELECT SG_CODE
  FROM WEBDBA.SG
  WHERE SG_NAME = 'HOO';
  SELECT SG_NAME AS GROUPNAME FROM WEBDBA.SG WHERE SG_NAME = 'HoonZzang';
/*
  F2. STEP2.JSP :: 상점등록 << GROUPCODE
     STORES
        STORECODE STORENAME STOREZIPCODE STOREADDR 
        STOREADDRDETAIL STOREPHONE + GROUPCODE
        B2-1. [INS:ST] ST_CODE ST_NAME ST_ZIPCODE ST_ADDR ST_ADDRDETAIL 
                  ST_PHONE GROUPCODE
        B2-2. [INS:SC : L1 L2 L3] STORECODE SC_CODE SC_NAME
              [SEL] SC_CODE, SC_NAME
  F3. STEP3.JSP :: 직원등록 << STORECODE SCCODE[] SCNAME[]
     STOREEMPLOYEES
        STORECODE SCCODE EMPNAME EMPPIN
        B3-1. [SEL] MAX(TO_NUMBER(SE_CODE)) + 1 AS EMPCODE
        B3-2. [INS] STORECODE, EMPCODE, SCCODE, EMPNAME, EMPPIN
  TRANSACTION END
  */
  
  SELECT NVL(MAX(SE_CODE), '000') FROM WEBDBA.SE;
  
  SELECT * FROM WEBDBA.SG;
  SELECT * FROM WEBDBA.ST;
  SELECT * FROM WEBDBA.SC;
  SELECT * FROM WEBDBA.SE;

/* 중복검사를 위한 임시 저장 테이블 */
CREATE TABLE TEMP(
  TEMP_GROUPNAME    NVARCHAR2(20)   NOT NULL
)TABLESPACE USERS;

-- GRANT
GRANT SELECT, INSERT, DELETE ON WEBDBA.TEMP TO WEBDEV;
-- 중복체크 VIEW
CREATE OR REPLACE VIEW DUPGROUPNAME
AS
SELECT SG_NAME AS GROUPNAME FROM WEBDBA.SG
UNION 
SELECT TEMP_GROUPNAME AS GROUPNAME FROM WEBDBA.TEMP;
  -- GRANT
  GRANT SELECT ON WEBDBA.DUPGROUPNAME TO WEBDEV;
SELECT * FROM WEBDBA.DUPGROUPNAME WHERE GROUPNAME = 'Hoon';
-- 중복이 안된 경우 TEMP테이블 INSERT
INSERT INTO WEBDBA.TEMP(TEMP_GROUPNAME) VALUES('Hoon');
COMMIT;

-- 취소시
DELETE FROM WEBDBA.TEMP WHERE TEMP_GROUPNAME = 'Hoon';
COMMIT;

-- 최종 확정 시
INSERT INTO WEBDBA.SG(SG_CODE, SG_NAME, SG_CEO, SG_PIN) VALUES();
DELETE FROM WEBDBA.TEMP WHERE TEMP_GROUPNAME = 'Hoon';
COMMIT;

SELECT * FROM WEBDBA.TEMP;
SELECT * FROM WEBDBA.SG;
SELECT * FROM WEBDBA.ST;
SELECT * FROM WEBDBA.SC;
DELETE FROM WEBDBA.TEMP;
DELETE FROM WEBDBA.SC;
DELETE FROM WEBDBA.ST;
DELETE FROM WEBDBA.SG;
COMMIT;

/* 로그인 */
SELECT * FROM WEBDBA.SG;
 -- S1000034	HoonZzang	후니	123456
SELECT * FROM WEBDBA.ST;
 -- 1234567890	후니네	22223	인천광역시 미추홀구 매소홀로488번길	6-3	01056808050		S1000034
SELECT * FROM WEBDBA.SC;
 /* 1234567890	L1	그룹대표
    1234567890	L2	매니저
    1234567890	L3	직원    */
SELECT * FROM WEBDBA.SE;
 -- [INS]
 INSERT INTO WEBDBA.SE(SE_STCODE, SE_CODE, SE_SCLEV, SE_NAME, SE_PIN, SE_SICODE)
                VALUES('1234567890', '000', 'L1', '후니', '123456', NULL);
 COMMIT;

/* 로그인 [탐색] - [기록] - [탐색] */
-- [탐색] 로그인 가능여부? >> WEBDBA.SE
   -- 1. 상점코드 여부 확인
   SELECT COUNT(*) FROM ST WHERE ST_CODE = '';
   -- 2. 직원 여부 확인
   SELECT COUNT(*) FROM SE WHERE SE_STCODE = '' AND SE_CODE = '';
   -- 3. 핀번호 확인
   SELECT COUNT(*) FROM SE WHERE (SE_STCODE = '' AND SE_CODE = '') AND SE_PIN = '';
   
-- [기록] 로그인 기록 >> WEBDBA.AL
  -- [INS] 
  INSERT INTO WEBDBA.AL(AL_SESTCODE, AL_SECODE, AL_DATE, AL_IP, AL_TYPE) 
                 VALUES( '', '', '', '', 1);
                 
-- [VIEW :: EMPINFO]
CREATE OR REPLACE VIEW ACCESSINFO
AS
SELECT  ST.ST_SGCODE AS GROUPCODE, SG.SG_NAME AS GROUPNAME, 
        SE.SE_STCODE AS STORECODE, ST.ST_NAME AS STORENAME, 
        ST.ST_ZIPCODE AS STOREZIP,  ST.ST_ADDR AS STOREADDR, ST.ST_ADDRDETAIL AS STOREADDRDETAIL,
        ST.ST_PHONE AS STOREPHONE, 
        SE.SE_CODE AS EMPCODE, SE.SE_NAME AS EMPNAME, SE.SE_SCL AS EMPLEVCODE, SC.SC_NAME AS LEVNAME,
        TO_CHAR(AL.ACCESSDATE, 'YYYYMMDDHH24MISS') AS ACCESSDATE, AL.ACCESSLOCATION AS ACCESSLOCATION
FROM (SELECT MAX(AL.AC_DATE) AS ACCESSDATE, AL.AC_IP AS ACCESSLOCATION, AL.AC_SESTCODE AS STORECODE, AL.AC_SECODE AS EMPCODE
        FROM ACCESSLOG AL WHERE AL.AC_TYPE = '1'
                          GROUP BY AL.AC_IP, AL.AC_SESTCODE, AL.AC_SECODE) AL 
        INNER JOIN SE SE ON AL.STORECODE = SE.SE_STCODE AND AL.EMPCODE = SE.SE_CODE
        INNER JOIN ST ST ON SE.SE_STCODE = ST.ST_CODE
        INNER JOIN SC SC ON ST.ST_CODE = SC.SC_STCODE
        INNER JOIN SG SG ON ST.ST_SGCODE = SG.SG_CODE ;
        
        commit;
-- GRANT 
GRANT SELECT ON WEBDBA.ACCESSINFO TO WEBDEV;
-- DEV
SELECT * FROM ACCESSINFO;
WHERE STORECODE = '' AND EMPCODE = '';
  
SELECT * FROM SE;

SELECT ST_CODE AS STORECODE, ST_NAME AS STORENAME FROM ST;
